// This file should contain a few features
// 1. An resizing or augmentation you do prior to training/testing
// 2. The labels of targets
// 3. The path to the model
// 4. The URL to the model
// 5. The SHAhash for where the model is stored (this can be found on Github)